### ISSUE TITLE
Script Execution Failure Due to CRLF Line Endings on Windows

### ISSUE THREAD

**Issue by anipnwr7777** [kalviumcommunity/compilerd#16]
## Issue Overview
When checking out the repository on a Windows system, script files are automatically converted to Windows-style line endings (CRLF). However, this causes problems when building a Docker image in a Linux environment, as Linux expects Unix-style line endings (LF).

## Steps to Reproduce
1. Clone the repository on a Windows machine.
2. Run a Docker build on the cloned repository.
3. Do a docker run and you will be able to see the issue.

**Comment by virajp4** [comment]
This can be fixed by selecting the End of Line sequence from the windows code editor such as VSCode.

**### Steps to fix (in VS Code) :-**
1) Press Control+Shift+P to open the Editor Commands.
2) Type and select "Change End of Line Sequence".
3) Select LF from the dropdown.

Fixes: #16

**Comment by anipnwr7777** [comment]
Hi, thanks for collaborating @virajp4. This solution effectively addresses the issue at the user level, but the focus is on resolving it for all future contributors without requiring user-level interference.

**Comment by virajp4** [comment]
The mentioned PR fixes that issue without requiring user-level interference.

**Comment by ishan9678** [comment]
I have followed 
https://github.com/kalviumcommunity/compilerd/issues/16
for fixing the issue with start.sh but it has not been resolved on windows/

This is the error - /usr/bin/start.sh: line 5: syntax error: unexpected end of file (expecting "then")

**Comment by virajp4** [comment]
> I have followed #16 for fixing the issue with start.sh but it has not been resolved on windows/
> 
> This is the error - /usr/bin/start.sh: line 5: syntax error: unexpected end of file (expecting "then")

Did you build the docker image again after making the changes? It would keep showing the error until you build the image again and run the container with the new image.
